{% set name = "ipyflow" %}
{% set version = "0.0.206" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipyflow-{{ version }}.tar.gz
  sha256: cd0c7b9a99c04fe8227ae8fc35976b063d2c0b5d73ff99cfd62601e5975363fa

build:
  entry_points:
    - ipyflow = ipyflow:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ipyflow-core =={{ version }}
    - jupyter
    - jupyterlab >=3.0
    - nbclassic
    - notebook

test:
  imports:
    - ipyflow
  commands:
    - pip check
    - ipyflow --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ipyflow/ipyflow
  summary: A reactive Python kernel for Jupyter notebooks.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
