{% set name = "ipyflow" %}
{% set version = "0.0.201" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyflow-{{ version }}.tar.gz
  sha256: 99878b3be67cb3e68ee08b1058cfd56bf410c7a7b99331dd68a6f6f3640b803c

build:
  entry_points:
    - ipyflow = ipyflow:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ipyflow-core ==0.0.200
    - jupyter
    - jupyterlab >=3.0
    - nbclassic
    - notebook

test:
  imports:
    - ipyflow
  commands:
    - pip check
    - ipyflow --help
  requires:
    - pip

about:
  home: https://github.com/ipyflow/ipyflow
  summary: A reactive Python kernel for Jupyter notebooks.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
