{% set name = "ipyflow" %}
{% set version = "0.0.207" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipyflow-{{ version }}.tar.gz
  sha256: 1e63a0c76ee29cfe36c144d86a25f3a281296c90506170c9abe777493663857a

build:
  entry_points:
    - ipyflow = ipyflow:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ipyflow-core =={{ version }}
    - jupyter
    - jupyterlab >=3.0
    - nbclassic
    - notebook

test:
  imports:
    - ipyflow
  commands:
    - pip check
    - ipyflow --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ipyflow/ipyflow
  summary: A reactive Python kernel for Jupyter notebooks.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
