schema_version: 1

context:
  name: ipyflow
  version: "0.0.228"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/8f/88/606f3a0fae75657b7bc2af8d149597f90acb18ed92d8f905c0425a9fcb4a/ipyflow-${{ version }}.tar.gz
  sha256: 97d82574c3869502e34307e9549addf8fb58b2d5162e1d328d56f7ba73f71206

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ipyflow = ipyflow:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - ipyflow-core ==${{ version }}
    - jupyter
    - jupyterlab >=3.0
    - nbclassic
    - notebook

tests:
  - python:
      imports:
        - ipyflow
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - ipyflow --help

about:
  summary: A reactive Python kernel for Jupyter notebooks.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/ipyflow/ipyflow

extra:
  recipe-maintainers:
    - thewchan
