schema_version: 1

context:
  name: ipyflow
  version: "0.0.230"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ipyflow-${{ version }}.tar.gz
  sha256: f67906851d72c25b868f4cbc30835a109364479efbf0f1122877d2b639bab3e3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ipyflow = ipyflow:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=48
    - wheel >=0.30.0
  run:
    - python >=${{ python_min }}
    - ipyflow-core ==${{ version }}
    - jupyter
    - jupyterlab >=3.0
    - nbclassic
    - notebook

tests:
  - python:
      imports:
        - ipyflow
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - ipyflow --help

about:
  summary: A reactive Python kernel for Jupyter notebooks.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/ipyflow/ipyflow

extra:
  recipe-maintainers:
    - thewchan
